const questions=[
{c:'Teóricos da Educação',q:'Para Paulo Freire, a educação libertadora se contrapõe principalmente à:',o:['Educação bancária','Avaliação diagnóstica','Gestão democrática','Aprendizagem colaborativa'],a:0,e:'Freire critica a educação bancária, na qual o professor deposita conteúdos. Defende diálogo, consciência crítica e práxis.'},
{c:'Teóricos da Educação',q:'Na teoria de Vygotsky, a Zona de Desenvolvimento Proximal representa:',o:['O que o aluno jamais aprenderá','A distância entre o que faz sozinho e com ajuda','Uma fase biológica fixa','O resultado final da avaliação'],a:1,e:'A ZDP indica a distância entre o desenvolvimento real e o potencial, alcançado com mediação.'},
{c:'Teóricos da Educação',q:'Segundo Piaget, a construção do conhecimento ocorre por meio de:',o:['Reforço e punição apenas','Assimilação e acomodação','Memorização mecânica','Imitação passiva'],a:1,e:'Assimilação e acomodação compõem o processo de adaptação e reorganização dos esquemas cognitivos.'},
{c:'Planejamento',q:'O planejamento escolar deve ser entendido como:',o:['Documento rígido e imutável','Processo contínuo, intencional e avaliável','Ato exclusivo da direção','Lista de conteúdos sem objetivos'],a:1,e:'Planejar é decidir intencionalmente, acompanhar e reorientar ações conforme o diagnóstico e os resultados.'},
{c:'Currículo',q:'O currículo oculto corresponde:',o:['À BNCC integral','A aprendizagens implícitas em relações e rotinas','Somente às disciplinas eletivas','Ao calendário escolar'],a:1,e:'O currículo oculto reúne valores, normas e comportamentos aprendidos implicitamente no cotidiano escolar.'},
{c:'Avaliação',q:'A principal finalidade da avaliação formativa é:',o:['Classificar ao fim do período','Punir baixo desempenho','Acompanhar e regular a aprendizagem','Eliminar a recuperação'],a:2,e:'A avaliação formativa fornece evidências durante o processo para orientar intervenções pedagógicas.'},
{c:'Legislação Educacional',q:'A gestão democrática do ensino público é um princípio previsto:',o:['Apenas em regimentos internos','Na Constituição Federal e na LDB','Somente no PNE municipal','Exclusivamente na BNCC'],a:1,e:'A gestão democrática integra os princípios constitucionais do ensino e também aparece na LDB.'},
{c:'PNE 2026',q:'Em um plano nacional de educação, uma meta deve ser acompanhada principalmente por:',o:['Slogans institucionais','Indicadores, prazos e estratégias','Decisões isoladas','Relatos sem evidências'],a:1,e:'Metas públicas exigem indicadores verificáveis, horizonte temporal e estratégias de implementação e monitoramento.'},
{c:'Inclusão',q:'O Atendimento Educacional Especializado deve:',o:['Substituir a escolarização comum','Complementar ou suplementar a formação','Separar todos os estudantes','Ocorrer apenas mediante reprovação'],a:1,e:'O AEE não substitui o ensino comum; oferece recursos e estratégias para eliminar barreiras à participação e aprendizagem.'},
{c:'Didática',q:'Uma sequência didática é melhor definida como:',o:['Atividades sem relação entre si','Conjunto articulado de atividades com objetivo de aprendizagem','Prova aplicada mensalmente','Plano administrativo anual'],a:1,e:'A sequência didática organiza atividades progressivas e articuladas em função de objetivos claros de aprendizagem.'}
];
const tracks=[...new Set(questions.map(x=>x.c))];let state=JSON.parse(localStorage.getItem('pdfQuiz')||'{"answered":0,"correct":0,"minutes":0,"streak":0,"goal":10}');let run=[],i=0,hits=0,answers=[],started=0;
const $=s=>document.querySelector(s);function save(){localStorage.setItem('pdfQuiz',JSON.stringify(state))}function show(id){['home','setup','quiz','result'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));if(id==='home')renderHome()}function renderHome(){$('#answered').textContent=state.answered;$('#accuracy').textContent=state.answered?Math.round(state.correct/state.answered*100)+'%':'0%';$('#minutes').textContent=state.minutes;$('#streak').textContent=state.streak;$('#goalDone').textContent=Math.min(state.answered,state.goal);$('#goalTotal').textContent=state.goal;$('#goalBar').style.width=Math.min(100,state.answered/state.goal*100)+'%';$('#tracks').innerHTML=tracks.map(t=>`<article><h3>${t}</h3><span>${state.answered?'Em andamento':'Não iniciado'}</span></article>`).join('')}
$('#category').innerHTML='<option value="Todas">Todas as áreas</option>'+tracks.map(x=>`<option>${x}</option>`).join('');$('#start').onclick=()=>show('setup');document.querySelectorAll('[data-to]').forEach(b=>b.onclick=()=>show(b.dataset.to));$('#reset').onclick=()=>{if(confirm('Deseja apagar todo o progresso deste dispositivo?')){state={answered:0,correct:0,minutes:0,streak:0,goal:10};save();renderHome()}};
$('#begin').onclick=()=>{let pool=$('#category').value==='Todas'?questions:questions.filter(x=>x.c===$('#category').value);run=[...pool].sort(()=>Math.random()-.5).slice(0,Math.min(+$ ('#amount').value,pool.length));i=hits=0;answers=[];started=Date.now();show('quiz');draw()};
function draw(){let x=run[i];$('#progressText').textContent=`Questão ${i+1} de ${run.length}`;$('#quizBar').style.width=(i/run.length*100)+'%';$('#tag').textContent=x.c;$('#prompt').textContent=x.q;$('#feedback').classList.add('hidden');$('#next').classList.add('hidden');$('#options').innerHTML=x.o.map((v,n)=>`<button class="option" data-n="${n}">${String.fromCharCode(65+n)}) ${v}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(+b.dataset.n))}
function answer(n){let x=run[i];document.querySelectorAll('.option').forEach((b,k)=>{b.disabled=true;if(k===x.a)b.classList.add('correct');if(k===n&&n!==x.a)b.classList.add('wrong')});if(n===x.a)hits++;answers.push({x,n});$('#feedback').innerHTML=`<strong>${n===x.a?'Acertou!':'Atenção:'}</strong> ${x.e}`;$('#feedback').classList.remove('hidden');$('#next').classList.remove('hidden')}
$('#next').onclick=()=>{if(++i<run.length)draw();else finish()};function finish(){let mins=Math.max(1,Math.round((Date.now()-started)/60000));state.answered+=run.length;state.correct+=hits;state.minutes+=mins;state.streak=Math.max(1,state.streak);save();let pct=Math.round(hits/run.length*100);$('#score').textContent=pct+'%';$('#summary').innerHTML=`<p>Você acertou <strong>${hits} de ${run.length}</strong> questões em ${mins} minuto(s).</p><p>${pct>=80?'Excelente desempenho. Avance para um simulado maior.':pct>=60?'Boa base. Revise os comentários antes do próximo simulado.':'Priorize a revisão dos assuntos com erro e tente novamente.'}</p>`;show('result')}
$('#report').onclick=()=>{let w=open('','_blank');w.document.write(`<title>Relatório PDF Concurso EDU</title><style>body{font:16px Arial;max-width:800px;margin:40px auto}h1{color:#b40d16}.q{border-bottom:1px solid #ddd;padding:15px 0}</style><h1>Relatório comentado — PDF Concurso EDU</h1><p>Resultado: ${hits}/${run.length}</p>${answers.map((a,j)=>`<div class=q><b>${j+1}. ${a.x.q}</b><p>Sua resposta: ${a.x.o[a.n]} — ${a.n===a.x.a?'CORRETA':'INCORRETA'}</p><p>Comentário: ${a.x.e}</p></div>`).join('')}<script>print()<\/script>`);w.document.close()};renderHome();setInterval(()=>{if(!$('#quiz').classList.contains('hidden')){let s=Math.floor((Date.now()-started)/1000);$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}},1000);
